"""
Cinematography & photography presets for Image Studio.

Data extracted from RenderZero Studio analysis + custom additions.
All dicts map slug -> prompt fragment (what gets injected into the prompt).
"""

# ── Directors (replacing "Movie Look/Aesthetic") ────────────────────────
# Maps director slug -> (display name, prompt fragment describing their visual style)

DIRECTORS = {
    "kubrick": ("Stanley Kubrick", "symmetrical one-point perspective compositions, cold clinical lighting, wide-angle lens distortion, meticulous set design"),
    "villeneuve": ("Denis Villeneuve", "amber desert tones, cyan shadows, clean contrast, vast empty landscapes, minimal grain, architectural compositions"),
    "nolan": ("Christopher Nolan", "IMAX-scale grandeur, practical lighting, desaturated palette with selective warm accents, deep focus sharp across the frame"),
    "fincher": ("David Fincher", "grimy greenish tint, low-key lighting, gritty grain, high contrast, precise symmetry, dark shadows"),
    "anderson-wes": ("Wes Anderson", "pastel palette, symmetrical polish, soft contrast, playful tint, perfectly centered framing, storybook aesthetic"),
    "tarkovsky": ("Andrei Tarkovsky", "long contemplative shots, natural light, muted earth tones, water reflections, fog and mist, poetic decay"),
    "lynch": ("David Lynch", "surreal dreamlike atmosphere, harsh contrast, red and blue saturated accents, uncanny suburban settings, smoke and haze"),
    "wong-kar-wai": ("Wong Kar-wai", "lush saturated colors, step-printing motion blur, neon reflections on wet surfaces, romantic melancholy, warm amber tones"),
    "kurosawa": ("Akira Kurosawa", "dramatic weather elements, telephoto lens compression, dynamic movement, high contrast black and white, epic scale"),
    "coppola": ("Francis Ford Coppola", "warm amber low-key lighting, deep shadows, soft film grain, rich golden interiors, operatic grandeur"),
    "spielberg": ("Steven Spielberg", "warm backlighting, lens flare, emotional golden hour, awe and wonder, practical magic-hour light"),
    "ridley-scott": ("Ridley Scott", "atmospheric haze, practical rain and smoke, high contrast, industrial textures, monumental scale, cold blue-gray palette"),
    "scorsese": ("Martin Scorsese", "kinetic camera movement, saturated urban palette, tracking shots, gritty documentary realism mixed with stylization"),
    "tarantino": ("Quentin Tarantino", "bold saturated 1970s film palette, wide-angle compositions, theatrical lighting, retro grain and warm tones"),
    "carpenter": ("John Carpenter", "anamorphic widescreen, dark shadows, blue moonlight, practical fog, minimalist synth-driven tension"),
    "del-toro": ("Guillermo del Toro", "teal-green palette, soft glow, gentle contrast, dreamy haze, gothic fairy-tale ornament, warm amber accents"),
    "malick": ("Terrence Malick", "golden hour natural light, wide-angle close-ups, flowing movement, pastoral landscapes, magic-hour warmth"),
    "deakins": ("Roger Deakins (DP)", "naturalistic motivated lighting, single-source setups, atmospheric depth, clean compositions, subtle color grading"),
    "lubezki": ("Emmanuel Lubezki (DP)", "long unbroken takes, natural and available light, extreme wide-angle, fluid camera movement, golden backlight"),
    "storaro": ("Vittorio Storaro (DP)", "expressive color symbolism, warm-to-cool gradients, chiaroscuro drama, painterly compositions"),
    "miyazaki": ("Hayao Miyazaki", "lush hand-painted landscapes, soft watercolor clouds, pastoral wonder, detailed environmental storytelling"),
    "denis": ("Claire Denis", "intimate close-ups, fragmented editing, warm skin tones, sensory textures, abstract narrative"),
    "eggers": ("Robert Eggers", "cold natural light, desaturated palette, period-accurate detail, stark compositions, dread-filled negative space"),
    "refn": ("Nicolas Winding Refn", "neon-drenched darkness, bold red and blue, slow deliberate framing, hyperreal violence, glossy surfaces"),
    "jarmusch": ("Jim Jarmusch", "high contrast black and white, deadpan compositions, quiet empty urban spaces, dry minimalism"),
    "gondry": ("Michel Gondry", "handmade practical effects, bright saturated palette, whimsical camera tricks, lo-fi charm"),
    "zhao": ("Chloé Zhao", "golden hour magic light, vast open landscapes, documentary-style intimacy, naturalistic beauty"),
    "jordan-peele": ("Jordan Peele", "crisp clean compositions, unsettling symmetry, saturated suburban colors, lurking shadows in bright daylight"),
    "denis-v": ("Denis Villeneuve", "amber desert tones, cyan shadows, vast scale, minimal grain, architectural geometry"),
    "ari-aster": ("Ari Aster", "bright daylight horror, wide static frames, floral pastoral with dread, overhead shots, muted pastels"),
    "spike-lee": ("Spike Lee", "bold primary colors, dutch angles, direct-to-camera address, high energy, urban landscape"),
    "coen": ("Coen Brothers", "deep focus, precise framing, ironic Americana palette, exaggerated shadows, darkly comic compositions"),
    "cronenberg": ("David Cronenberg", "clinical sterile interiors, cold fluorescent lighting, unsettling body close-ups, muted institutional palette"),
    "bergman": ("Ingmar Bergman", "stark black and white, tight facial close-ups, minimal set design, theatrical lighting, existential stillness"),
    "almodovar": ("Pedro Almodovar", "vivid saturated reds and yellows, melodramatic interiors, Spanish baroque warmth"),
    "argento": ("Dario Argento", "giallo primary color lighting (red, blue, green gels), ornate architecture, baroque horror"),
    "bay": ("Michael Bay", "golden hour explosions, low-angle hero shots, teal-and-orange grading, IMAX spectacle"),
    "berkeley": ("Busby Berkeley", "kaleidoscopic overhead choreography, geometric human patterns, art deco musical spectacle"),
    "bertolucci": ("Bernardo Bertolucci", "warm amber interiors, sensual lighting, operatic camera movements, rich color"),
    "blomkamp": ("Neill Blomkamp", "documentary-style sci-fi, South African locations, gritty mechanical alien tech"),
    "boyle": ("Danny Boyle", "frenetic energy, oversaturated colors, rapid cuts implied through composition, urban grit"),
    "burton": ("Tim Burton", "gothic expressionist silhouettes, pale faces in dark worlds, spiraling architecture"),
    "cameron": ("James Cameron", "blue-tinted sci-fi technology, underwater bioluminescence, epic action scale"),
    "chow": ("Stephen Chow", "Hong Kong slapstick spectacle, exaggerated wire-fu, colorful comic energy"),
    "corman": ("Roger Corman", "low-budget atmospheric horror, bold color on black, drive-in aesthetic"),
    "cuaron": ("Alfonso Cuaron", "long unbroken takes, naturalistic light, intimate handheld mixed with sweeping crane shots"),
    "cunningham": ("Chris Cunningham", "cybernetic body horror, clinical white environments, unsettling flesh-meets-machine"),
    "de-palma": ("Brian De Palma", "split diopter shots, long tracking sequences, Hitchcock homage, bold primary colors, split screen"),
    "edwards": ("Gareth Edwards", "scale through obscured reveals, realistic handheld, human-dwarfed-by-spectacle"),
    "eisenstein": ("Sergei Eisenstein", "Soviet montage theory, dynamic diagonal compositions, revolutionary masses"),
    "fellini": ("Federico Fellini", "dreamlike carnival atmosphere, baroque excess, theatrical costumes, magical realism"),
    "ford": ("John Ford", "Monument Valley western landscapes, low-angle heroic shots, frontier mythology"),
    "gilliam": ("Terry Gilliam", "baroque dystopian clutter, wide-angle distortion, handmade whimsical sets"),
    "godard": ("Jean-Luc Godard", "French New Wave jump cuts implied, bold graphic text overlays, primary color pop art"),
    "greenaway": ("Peter Greenaway", "painterly tableaux, symmetrical compositions, numerical visual systems, old master lighting"),
    "harryhausen": ("Ray Harryhausen", "stop-motion creature drama, Dynamation compositing, classical mythology spectacle"),
    "hitchcock": ("Alfred Hitchcock", "precise storyboarded framing, suspense through composition, cool blonde subjects, voyeuristic camera"),
    "hughes": ("John Hughes", "warm suburban Americana, 1980s pastel interiors, emotional close-ups of teenage faces"),
    "hype-williams": ("Hype Williams", "music video excess, fisheye lens distortion, bold primary colors, bling aesthetic"),
    "inarritu": ("Alejandro Gonzalez Inarritu", "long continuous shots, raw emotional intensity, handheld realism, naturalistic lighting"),
    "jackson": ("Peter Jackson", "epic New Zealand landscapes, sweeping aerial vistas, fantasy grandeur"),
    "jeunet": ("Jean-Pierre Jeunet", "warm amber-green palette, whimsical mechanical details, fairy-tale Paris"),
    "jodorowsky": ("Alejandro Jodorowsky", "psychedelic surrealism, vivid saturated religious imagery, bizarre symmetrical compositions"),
    "jonze": ("Spike Jonze", "surreal lo-fi whimsy, practical in-camera effects, warm human oddity"),
    "kashyap": ("Anurag Kashyap", "gritty Indian urban realism, handheld rawness, dark saturated palette"),
    "kitano": ("Takeshi Kitano", "deadpan minimalist framing, sudden violence, cool blue Japanese urban"),
    "lang": ("Fritz Lang", "German expressionist shadows, geometric compositions, monumental architecture, Metropolis scale"),
    "lanthimos": ("Yorgos Lanthimos", "distorted wide-angle compositions, cold sterile interiors, uncomfortable symmetry, deadpan absurdism"),
    "lean": ("David Lean", "vast landscape panoramas, epic scale, precise classical compositions, Lawrence of Arabia grandeur"),
    "leone": ("Sergio Leone", "extreme close-up eyes, vast widescreen desert, operatic standoff compositions"),
    "lucas": ("George Lucas", "retro-futuristic lived-in worlds, mythic compositions, warm golden tones mixed with alien palettes"),
    "luc-besson": ("Luc Besson", "sleek European action, saturated urban neon, stylish genre filmmaking"),
    "mann": ("Michael Mann", "nocturnal urban photography, precise digital clarity, cold blue cityscapes at night"),
    "mendes": ("Sam Mendes", "one-shot continuity, stage-like compositions, suburban beauty in banality"),
    "miike": ("Takashi Miike", "extreme Japanese genre excess, shocking imagery, hyperviolent saturated color"),
    "miller": ("George Miller", "kinetic vehicular chaos, warm desert orange, dusty practical stunts, explosive color"),
    "nair": ("Mira Nair", "vibrant South Asian color, warm golden interiors, rich textile patterns"),
    "ozu": ("Yasujiro Ozu", "low tatami-level camera, centered symmetrical interiors, quiet domestic compositions"),
    "peckinpah": ("Sam Peckinpah", "slow-motion violence ballet, dusty western grit, moral ambiguity"),
    "polanski": ("Roman Polanski", "claustrophobic interiors, paranoid framing, unsettling negative space"),
    "pta": ("Paul Thomas Anderson", "anamorphic widescreen, long steady tracking shots, 1970s period warmth, ensemble staging"),
    "raimi": ("Sam Raimi", "dynamic low-angle tracking, comic book energy, practical horror effects"),
    "rajamouli": ("S.S. Rajamouli", "Indian epic spectacle, slow-motion heroic action, mythological visual scale"),
    "ray-satyajit": ("Satyajit Ray", "humanist Indian realism, natural light, contemplative rural compositions"),
    "ritchie": ("Guy Ritchie", "kinetic freeze-frame compositions, gritty British urban palette, stylized masculine energy"),
    "roeg": ("Nicolas Roeg", "fragmented non-linear imagery, arid desert landscapes, disorienting visual editing"),
    "romero": ("George Romero", "low-budget 16mm grit, documentary horror realism, green-gray pallor"),
    "scott-coppola-sofia": ("Sofia Coppola", "pastel dreamlike interiors, feminine melancholy, soft natural light, indie film grain"),
    "sednaoui": ("Stephane Sednaoui", "fashion-forward music video aesthetic, bold saturated editorial"),
    "singh": ("Tarsem Singh", "art-directed fantasy spectacle, costume drama opulence, painterly compositions"),
    "snyder": ("Zack Snyder", "speed-ramped slow motion, high contrast desaturation, mythic muscular compositions"),
    "tati": ("Jacques Tati", "precise visual comedy framing, modernist architecture, deadpan wide shots"),
    "tsui-hark": ("Tsui Hark", "kinetic Hong Kong action, wire-work martial arts, mythic Chinese fantasy color"),
    "verhoeven": ("Paul Verhoeven", "satirical sci-fi excess, glossy violence, hyper-real corporate futures"),
    "von-trier": ("Lars Von Trier", "Dogme handheld rawness, desaturated emotional devastation, confrontational framing"),
    "weir": ("Peter Weir", "atmospheric natural landscapes, soft mist and haze, contemplative Australian light"),
    "wilder": ("Billy Wilder", "crisp black and white noir, sharp compositions, witty visual storytelling, Hollywood classical framing"),
    "woo": ("John Woo", "slow-motion dual-wielding action, doves in flight, church interiors with candlelight"),
    "zemeckis": ("Robert Zemeckis", "warm nostalgic Americana, visual effects innovation, golden suburban lighting"),
}

# ── Photographers ───────────────────────────────────────────────────────

PHOTOGRAPHERS = {
    "7th-era": "7th Era", "alberto-seveso": "Alberto Seveso", "alec-soth": "Alec Soth",
    "alen-palander": "Alen Palander", "alex-strohl": "Alex Strohl", "alex-webb": "Alex Webb",
    "alfred-stieglitz": "Alfred Stieglitz", "ando-fuchs": "Ando Fuchs",
    "andreas-gursky": "Andreas Gursky", "anne-brigman": "Anne Brigman",
    "annie-leibovitz": "Annie Leibovitz", "ansel-adams": "Ansel Adams",
    "august-sander": "August Sander", "barbara-kruger": "Barbara Kruger",
    "benjamin-hardman": "Benjamin Hardman", "bernd-hilla-becher": "Bernd and Hilla Becher",
    "bill-brandt": "Bill Brandt", "brandon-woelfel": "Brandon Woelfel",
    "bryan-schutmaat": "Bryan Schutmaat", "chris-burkard": "Chris Burkard",
    "chris-friel": "Chris Friel", "chris-hau": "Chris Hau",
    "cindy-sherman": "Cindy Sherman", "daido-moriyama": "Daido Moriyama",
    "daniel-schiffer": "Daniel Schiffer", "david-lachapelle": "David LaChapelle",
    "david-yarrow": "David Yarrow", "dorothea-lange": "Dorothea Lange",
    "dylan-furst": "Dylan Furst", "elliott-erwitt": "Elliott Erwitt",
    "eugene-atget": "Eugène Atget", "fan-ho": "Fan Ho",
    "garry-winogrand": "Garry Winogrand", "george-hurrell": "George Hurrell",
    "germaine-krull": "Germaine Krull", "gregory-crewdson": "Gregory Crewdson",
    "guy-bourdin": "Guy Bourdin", "hans-bellmer": "Hans Bellmer",
    "helmut-newton": "Helmut Newton", "henri-cartier-bresson": "Henri Cartier-Bresson",
    "herb-ritts": "Herb Ritts", "hiroshi-sugimoto": "Hiroshi Sugimoto",
    "irene-rudnyk": "Irene Rudnyk", "james-bidgood": "James Bidgood",
    "jeff-wall": "Jeff Wall", "jerry-uelsmann": "Jerry Uelsmann",
    "jord-hammond": "Jord Hammond", "jordi-koalitic": "Jordi Koalitic",
    "juergen-teller": "Juergen Teller", "julia-trotti": "Julia Trotti",
    "kim-keever": "Kim Keever", "laszlo-moholy-nagy": "László Moholy-Nagy",
    "lee-friedlander": "Lee Friedlander", "liam-wong": "Liam Wong",
    "lotte-reiniger": "Lotte Reiniger", "man-ray": "Man Ray",
    "mango-street": "Mango Street", "manny-ortiz": "Manny Ortiz",
    "martin-schoeller": "Martin Schoeller", "mary-ellen-mark": "Mary Ellen Mark",
    "michael-kenna": "Michael Kenna", "mickalene-thomas": "Mickalene Thomas",
    "miko-lagerstedt": "Miko Lagerstedt", "miles-aldridge": "Miles Aldridge",
    "misha-gordin": "Misha Gordin", "nadav-kander": "Nadav Kander",
    "nan-goldin": "Nan Goldin", "nathan-wirth": "Nathan Wirth",
    "nick-knight": "Nick Knight", "northborders": "Northborders",
    "oleg-oprisco": "Oleg Oprisco", "paolo-roversi": "Paolo Roversi",
    "peter-lindbergh": "Peter Lindbergh", "peter-mckinnon": "Peter McKinnon",
    "philip-lorca-dicorcia": "Philip-Lorca diCorcia", "platon": "Platon",
    "rankin": "Rankin", "rehahn": "Réhahn", "reuben-wu": "Reuben Wu",
    "richard-avedon": "Richard Avedon", "rinko-kawauchi": "Rinko Kawauchi",
    "robert-capa": "Robert Capa", "robert-frank": "Robert Frank",
    "saul-leiter": "Saul Leiter", "sebastiao-salgado": "Sebastião Salgado",
    "sorelle-amore": "Sorelle Amore", "stephen-shore": "Stephen Shore",
    "steve-mccurry": "Steve McCurry", "thomas-struth": "Thomas Struth",
    "tim-walker": "Tim Walker", "todd-hido": "Todd Hido",
    "tyler-shields": "Tyler Shields", "vivian-maier": "Vivian Maier",
    "w-eugene-smith": "W. Eugene Smith", "walker-evans": "Walker Evans",
    "william-eggleston": "William Eggleston", "wolfgang-tillmans": "Wolfgang Tillmans",
    "yousuf-karsh": "Yousuf Karsh", "zanele-muholi": "Zanele Muholi",
}

# ── Cameras ─────────────────────────────────────────────────────────────

CAMERAS = {
    # Cinema cameras
    "arri-alexa": "ARRI ALEXA 65 cinema camera",
    "red": "RED digital cinema camera",
    "panavision": "Panavision Panaflex cinema camera",
    "sony-venice": "Sony Venice cinema camera",
    "sony-fx6": "Sony FX6 cinema camera",
    "canon-c500": "Canon C500 cinema camera",
    "aaton-xtr": "Aaton XTR 16mm cinema camera",
    "bolex": "Bolex H16 16mm film camera",
    "8mm": "8mm film camera",
    "16mm": "s16mm film camera",
    "35mm": "35mm film camera",
    # Digital
    "canon-5d": "Canon EOS 5D digital SLR",
    "fuji-xt4": "Fujifilm X-T4 mirrorless",
    "gopro": "GoPro Hero wide-angle action camera",
    "hasselblad-x1d": "Hasselblad X1D II medium format digital",
    "insta360": "Insta360 X4 360-degree camera",
    "leica-q2": "Leica Q2 Monochrom",
    "lumix-gh5": "Lumix GH5 mirrorless",
    "pentax-645z": "Pentax 645Z medium format digital",
    "phase-one": "Phase One XF IQ4 150MP digital back",
    "sony-fx3": "Sony FX3 full-frame cinema",
    # Classic film
    "canon-ae1": "Canon AE-1 35mm film camera",
    "contax-t2": "Contax T2 compact film camera",
    "diana": "Diana F+ toy camera",
    "hasselblad-500": "Hasselblad 500CM medium format",
    "holga": "Holga 120N toy camera with light leaks",
    "kodak-brownie": "Kodak Brownie vintage box camera",
    "leica-m3": "Leica M3 rangefinder",
    "lomo-lca": "Lomo LC-A lomography camera",
    "mamiya-rb67": "Mamiya RB67 medium format",
    "minolta-srt": "Minolta SRT-101 SLR",
    "nikon-f2": "Nikon F2 professional SLR",
    "nikon-fm2": "Nikon FM2 manual SLR",
    "olympus-om1": "Olympus OM-1 compact SLR",
    "pentax-k1000": "Pentax K1000 manual SLR",
    "polaroid-600": "Polaroid 600 instant camera",
    "polaroid-sx70": "Polaroid SX-70 instant camera",
    "rolleiflex": "Rolleiflex twin-lens reflex medium format",
    "yashica-t4": "Yashica T4 compact film camera",
    "zenit-e": "Zenit-E Soviet SLR",
    # Modern consumer
    "iphone": "iPhone Pro smartphone camera",
    "android": "old Android phone camera",
    "doorbell": "doorbell security camera",
    "security": "low-resolution security camera",
    "webcam": "modern 1080p webcam",
    "vhs": "VHS camcorder",
    "kodak-funsaver": "Kodak FunSaver disposable camera",
}

# ── Lighting ────────────────────────────────────────────────────────────

LIGHTING = {
    "backlight": "Backlighting / Rim Lighting creating silhouette edge glow",
    "blue-hour": "Blue hour twilight with cool ambient tones",
    "bounce": "Bounce Lighting with soft reflected fill",
    "broad": "Broad Lighting illuminating the wider side of the face",
    "candlelight": "Candlelight Lighting with warm flicker and deep surrounding shadows",
    "chiaroscuro": "Chiaroscuro Lighting with a single hard key and heavy shadow contrast",
    "color-gels": "Color Gels creating tinted dramatic lighting",
    "direct-flash": "Direct on-camera flash creating harsh shadows and flat artificial look",
    "fog-diffusion": "Fog diffusion with atmospheric haze softening light",
    "gobo": "Gobo Lighting casting patterned shadows",
    "golden-hour": "Golden hour warm sunlight with long shadows",
    "hard": "Hard Lighting with crisp punchy shadows",
    "high-key": "High Key Lighting, bright and even, minimal shadows",
    "led-street": "LED streetlights with cool white urban illumination",
    "loop": "Loop Lighting with shadow falling slightly below and to the side of the nose",
    "low-key": "Low Key Lighting with dramatic shadows and moody atmosphere",
    "midday-sun": "Harsh midday sun lighting with strong overhead shadows",
    "moonlight": "Moonlight with cool blue-silver tones, nocturnal",
    "motivated": "Motivated Lighting justified by visible sources in the scene",
    "natural": "Natural daylight, ambient and organic",
    "neon": "Neon Lighting from colorful artificial light sources",
    "open-shade": "Open shade skylight, soft and even",
    "overcast": "Overcast flat lighting with muted tones",
    "paramount": "Paramount Lighting with high centered key and soft shadow under the nose",
    "phone-flash": "Phone flashlight creating harsh handheld illumination",
    "practical": "Practical Lighting from visible light sources in the scene",
    "product-side": "Product side key for commercial photography",
    "rembrandt": "Rembrandt Lighting with triangle of light on shadowed cheek",
    "rim-soft-fill": "Rim light with soft fill, separating subject from background",
    "ring-light": "Ring light creating even front illumination with circular catchlights",
    "shopfront": "Shopfront fluorescents with commercial ambient glow",
    "silhouette": "Silhouette Shadows, subject as dark shape against bright background",
    "sodium-street": "Sodium streetlamps with warm orange urban glow",
    "soft": "Soft diffused lighting with gentle gradients",
    "softbox": "Softbox key lighting for studio portrait",
    "split": "Split Lighting illuminating exactly half the face",
    "teal-orange": "Teal-and-orange cinematic contrast lighting",
    "three-point": "Three-point lighting with soft key, gentle fill, and clean rim light",
    "top": "Top Lighting with overhead key and subtle fill",
    "top-down-flat": "Top-down flat lay diffuse lighting for product shots",
    "underlight": "Underlighting casting upward shadows for dramatic effect",
    "volumetric": "Volumetric Lighting with visible light rays through atmosphere",
    "window": "Window spill with soft directional natural light",
}

# ── Shot Types ──────────────────────────────────────────────────────────

SHOT_TYPES = {
    "birds-eye": "Bird's-eye view from directly above",
    "close-up": "Close up shot",
    "cutaway": "Cutaway shot of a detail",
    "cowboy": "Cowboy shot framed from mid-thigh up",
    "dutch": "Dutch angle tilted frame",
    "full-body": "Entire body full-length shot",
    "establishing": "Wide establishing shot showing location",
    "extreme-close-up": "Extreme close up shot of fine detail",
    "group": "Group shot with multiple subjects",
    "headshot": "Headshot portrait, head and shoulders",
    "high-angle": "High angle shot looking down at subject",
    "insert": "Insert shot of specific object or detail",
    "low-angle": "Low angle shot looking up at subject",
    "medium": "Medium shot from waist up",
    "ots": "Over the shoulder shot",
    "overhead": "Overhead bird's eye view",
    "pov": "Point of view first-person shot",
    "reaction": "Reaction shot capturing emotional response",
    "reverse": "Reverse shot showing opposite perspective",
    "three-quarter": "Three quarter body shot",
    "tight-headshot": "Tight headshot, face fills frame",
    "two-shot": "Two-shot framing two subjects",
    "upper-body": "Upper body shot from chest up",
    "wide": "Wide shot showing full scene",
    "worms-eye": "Worm's-eye view from ground level looking up",
    "macro": "Macro extreme detail shot",
}

# ── Lens Types ──────────────────────────────────────────────────────────

LENS_TYPES = {
    "anamorphic": "Anamorphic Cinema Lens with oval bokeh and horizontal flare",
    "catadioptric": "Catadioptric (Mirror) Lens with donut-shaped bokeh",
    "fisheye": "Fisheye Lens with extreme barrel distortion",
    "helios": "Helios 44-2 with signature swirly bokeh",
    "holga": "Holga Style Lens with soft vignette and blur",
    "lensbaby": "Lensbaby / Selective Focus with tilt blur",
    "macro": "Macro Lens for extreme close-up detail",
    "petzval": "Petzval Portrait Lens with sharp center and swirly blur",
    "soft-focus": "Soft-Focus Portrait Lens with dreamy glow",
    "tilt-shift": "Tilt-Shift Lens with selective focus plane",
    "toy": "Toy Plastic Lens with lo-fi imperfections",
    "voigtlander": "Voigtländer Nokton 50mm f1.1 with extreme shallow depth",
}

# ── Focal Lengths ───────────────────────────────────────────────────────

FOCAL_LENGTHS = {
    "8": "8mm fisheye ultra-wide with extreme barrel distortion",
    "14": "14mm ultra wide angle",
    "24": "24mm wide angle",
    "35": "35mm wide standard",
    "50": "50mm standard natural perspective",
    "85": "85mm portrait with flattering compression",
    "100": "100mm macro",
    "200": "200mm super telephoto with strong compression",
    "300": "300mm extreme telephoto",
}

# ── Film Stocks ─────────────────────────────────────────────────────────

FILM_STOCKS = {
    "agfa-vista": "Agfa Vista, warm tones with slight green shift",
    "cinestill-50d": "CineStill 50D, daylight-balanced cinema film, fine grain, warm tones",
    "cinestill-800t": "CineStill 800T, tungsten-balanced with halation glow around highlights",
    "ektachrome-e100": "Ektachrome E100, fine grain slide film with cool clean tones",
    "ektar-100": "Kodak Ektar 100, vivid saturated colors, ultra-fine grain",
    "fuji-acros": "Fuji Acros 100, fine grain black and white with smooth tones",
    "fuji-pro-400h": "Fuji Pro 400H, soft pastel tones, gentle skin rendering",
    "fuji-superia": "Fuji Superia 400, warm consumer film with green-yellow cast",
    "fujicolor-pro": "Fujicolor Pro, balanced professional color negative",
    "hp5": "Ilford HP5 Plus 400, classic black and white with versatile grain",
    "ilford-delta": "Ilford Delta, modern black and white with controlled grain",
    "ilford-xp2": "Ilford XP2 Super, chromogenic black and white, smooth tones",
    "kodachrome-64": "Kodachrome 64, legendary rich saturated colors, warm shadows, fine grain",
    "kodak-gold": "Kodak Gold 200, warm amateur film with nostalgic look",
    "kodak-ultramax": "Kodak UltraMax 400, punchy saturated consumer film",
    "kodak-vision3-500t": "Kodak Vision3 500T, tungsten cinema stock, blue-tinted shadows",
    "kodak-vision3-imax": "Kodak Vision3 IMAX, massive format cinema stock",
    "lomo-berlin": "Lomography Berlin Kino B&W, contrasty monochrome",
    "lomo-color-tiger": "Lomography Color Tiger, wild unpredictable color shifts",
    "lomo-lady-grey": "Lomography Lady Grey 400, soft black and white",
    "lomo-lobster": "Lomography Lobster Redscale, warm red-orange shifted tones",
    "lomo-purple": "Lomography Purple, purple-shifted experimental color",
    "portra-160": "Kodak Portra 160, fine grain, soft natural skin tones",
    "portra-400": "Kodak Portra 400, warm skin tones, fine grain, industry standard portrait film",
    "portra-800": "Kodak Portra 800, high-speed portrait film with visible grain",
    "provia-100f": "Fuji Provia 100F, natural color slide film with fine grain",
    "tri-x": "Kodak Tri-X 400, legendary black and white with classic grain structure",
    "velvia-100": "Fuji Velvia 100, extreme color saturation, vivid greens and blues",
}

# ── Filters / Effects ───────────────────────────────────────────────────

FILTERS = {
    "bw": "Black and white, fully desaturated",
    "black-mist": "Black mist filter, softened highlights with dreamy glow",
    "bloom": "Bloom glow on bright areas",
    "bokeh": "Shallow depth of field with bokeh blur",
    "scanlines": "CRT scanline overlay",
    "chromatic": "Chromatic aberration color fringing on edges",
    "collage": "Collage cutout mixed-media effect",
    "color-filter": "Color filter tint overlay",
    "cross-process": "Cross-processed unexpected color shift",
    "cyanotype": "Cyanotype blue monochrome print",
    "datamosh": "Datamosh glitch digital corruption",
    "desaturated-grunge": "Desaturated grunge with faded worn textures",
    "dreamy-haze": "Dreamy haze with soft atmospheric diffusion",
    "duotone": "Duotone two-color mapping",
    "grain": "Film grain texture overlay",
    "glitch": "Glitch style digital artifact effect",
    "hdr": "HDR tone mapping, expanded dynamic range",
    "halftone": "Halftone dot pattern print effect",
    "hologram": "Hologram effect with iridescent transparency",
    "infrared": "Infrared filter with false color foliage",
    "kaleidoscope": "Kaleidoscope mirrored symmetry pattern",
    "lens-flare": "Lens flare from bright light source",
    "light-leaks": "Warm light leak artifacts bleeding from edges",
    "liquify": "Liquify smear distortion effect",
    "long-exposure": "Long exposure light trails and motion blur",
    "mirror-split": "Mirror split bilateral symmetry",
    "motion-blur": "Motion blur for movement and speed",
    "nd-filter": "ND filter with extended exposure, smooth water and clouds",
    "newspaper": "Newspaper print dot matrix reproduction",
    "cmyk-offset": "Off-register CMYK print with color separation misalignment",
    "orton": "Orton glow with sharp-soft double exposure blend",
    "overexposed": "Intentionally overexposed, washed out bright",
    "xerox": "Photocopy / Xerox high contrast degraded reproduction",
    "pixel-sort": "Pixel sort glitch art data-bent effect",
    "posterized": "Posterized reduced color palette, flat tones",
    "radial-blur": "Radial blur zoom effect from center",
    "risograph": "Risograph print with spot color and texture grain",
    "selective-color": "Selective color with one hue preserved in desaturated scene",
    "sepia": "Sepia tone warm monochrome vintage",
    "soft-focus": "Soft focus dreamy diffusion",
    "solarized": "Solarized Sabattier effect with inverted tones",
    "split-tone": "Split tone with different tints in highlights and shadows",
    "underexposed": "Intentionally underexposed, dark moody",
    "vignette": "Dark vignette around edges drawing focus to center",
}

# ── Aspect Ratios ───────────────────────────────────────────────────────

ASPECT_RATIOS = {
    "1:1": (1024, 1024),
    "3:4": (768, 1024),
    "4:3": (1024, 768),
    "9:16": (576, 1024),
    "16:9": (1024, 576),
    "21:9": (1024, 439),
    "2.39:1": (1024, 428),
}

# ── Camera Movements ───────────────────────────────────────────────────

CAMERA_MOVEMENTS = {
    "dolly-in": "Dolly in, camera physically moves closer to the subject",
    "dolly-out": "Dolly out, camera physically pulls away from the subject",
    "zoom-in": "Zoom in, lens focal length changes to magnify the subject",
    "zoom-out": "Zoom out, lens focal length widens to reveal more of the scene",
    "tracking": "Tracking shot, camera moves alongside the subject in the same direction",
    "handheld": "Handheld camera, natural slight shakiness without stabilization",
    "static": "Static shot, camera fixed in one position with no movement",
    "orbit-right": "Orbit right, camera moves in a semicircle around the subject",
    "orbit-left": "Orbit left, camera moves in a semicircle around the subject",
    "pan-right": "Pan right, camera rotates horizontally to the right on fixed base",
    "pan-left": "Pan left, camera rotates horizontally to the left on fixed base",
    "tilt-up": "Tilt up, camera rotates vertically upward on fixed base",
    "tilt-down": "Tilt down, camera rotates vertically downward on fixed base",
    "crane-up": "Crane up, camera rises vertically revealing the scene from above",
    "crane-down": "Crane down, camera descends vertically into the scene",
    "steadicam": "Steadicam, smooth floating camera movement following the subject",
    "whip-pan": "Whip pan, extremely fast horizontal camera turn creating motion blur",
    "push-in": "Push in, slow deliberate move toward a character or detail",
    "pull-out": "Pull out, slow reveal moving away from a detail to show context",
}


def list_options(category: str) -> str:
    """List all options for a given category, formatted for terminal output."""
    data = {
        "directors": {k: f"{v[0]}" for k, v in DIRECTORS.items()},
        "photographers": PHOTOGRAPHERS,
        "cameras": CAMERAS,
        "lighting": LIGHTING,
        "shots": SHOT_TYPES,
        "lenses": LENS_TYPES,
        "focal-lengths": FOCAL_LENGTHS,
        "film-stocks": FILM_STOCKS,
        "filters": FILTERS,
        "aspect-ratios": {k: f"{v[0]}x{v[1]}" for k, v in ASPECT_RATIOS.items()},
        "camera-movements": CAMERA_MOVEMENTS,
    }

    if category == "all":
        lines = []
        for cat_name, cat_data in data.items():
            lines.append(f"\n=== {cat_name.upper()} ({len(cat_data)}) ===")
            for k, v in cat_data.items():
                desc = v if isinstance(v, str) else str(v)
                short = desc[:60] + "..." if len(desc) > 60 else desc
                lines.append(f"  {k:<25} {short}")
        return "\n".join(lines)

    cat = data.get(category)
    if not cat:
        return f"Unknown category '{category}'. Available: {', '.join(data.keys())}"

    lines = [f"=== {category.upper()} ({len(cat)}) ==="]
    for k, v in cat.items():
        desc = v if isinstance(v, str) else str(v)
        short = desc[:65] + "..." if len(desc) > 65 else desc
        lines.append(f"  {k:<25} {short}")
    return "\n".join(lines)
